Demo.PL/Controllers/DepartmentController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.BLL.Repositories;
using Demo.DAL.Models;
using Demo.PL.viewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using System.Collections.Generic;
using System.Net.NetworkInformation;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly  IUnitOfWork _unitOfWork;//Aggregation Relationship
        private readonly IMapper _mapper;

        public DepartmentController(IUnitOfWork unitOfWork ,IMapper mapper) //Ask CLR For Creating Object From Class Implement The Interface IDepartmentRepository
        {
            _unitOfWork=unitOfWork;
            _mapper = mapper;
        }

        // BasURL/Department/Index
        public async Task<IActionResult> Index()
        {
            var departments = await _unitOfWork.DepartmentRepository.GetAll();
            var MappedDepartment = _mapper.Map<IEnumerable<Department>,IEnumerable<DepartmentViewModel>>(departments);
             
            return View(MappedDepartment);
        }

        [HttpGet]
        public IActionResult Create() 
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create( DepartmentViewModel departmentVM)
        {
            if (ModelState.IsValid) //Server Side Validation
            {
                var MappedDepartment = _mapper.Map<DepartmentViewModel, Department>(departmentVM);
                await _unitOfWork.DepartmentRepository.Add(MappedDepartment);
                int Result = await _unitOfWork.Complete();
                //TempData => Dictionary Object
                //Transfer Data From Action To Action
                if (Result >0)
                {
                    TempData["Message"] = $"Department {departmentVM.Name} is Created ";
                }
                
                return RedirectToAction(nameof(Index));
            }
            return View(departmentVM);
        }

        public async Task<IActionResult> Details(int? id , string ViewName = "Details" )
        {
            if (id is null)
              return BadRequest();//Status Code 400
            
            var department = await _unitOfWork.DepartmentRepository.GetById(id.Value);
            if (department is null)
                return NotFound();
            var MappedDepartments = _mapper.Map<Department, DepartmentViewModel>(department);
            return View(ViewName, MappedDepartments);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            //if (id is null)
            //    return BadRequest();

            //var department = _departmentRepository.GetById(id.Value);
            //if (department is null)
            //    return NotFound();
            //return View(department);
            return await Details(id , "Edit");

        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(DepartmentViewModel departmentVM , [FromRoute] int id )
        {
            if (id != departmentVM.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    var MappedDepartment = _mapper.Map<DepartmentViewModel,Department>(departmentVM);
                    _unitOfWork.DepartmentRepository.Update(MappedDepartment);
                    await _unitOfWork.Complete();
                    return RedirectToAction(nameof(Index));
                }
                catch (System.Exception ex)
                {

                    ModelState.AddModelError(string.Empty, ex.Message);
                }

            }
                return View(departmentVM);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int? id) 
        {
            return await Details(id, "Delete");

        }

        public async  Task<IActionResult> Delete(DepartmentViewModel departmentVM, [FromRoute] int id)
        {
           if(id != departmentVM.Id)
                return BadRequest();
            try
            {
                var MappedDepartment = _mapper.Map<DepartmentViewModel, Department>(departmentVM);
                _unitOfWork.DepartmentRepository.Delete(MappedDepartment);
                await _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }
            catch (System.Exception ex )
            {
                ModelState.AddModelError(string.Empty,ex.Message);
                return View(departmentVM);
            }


        }

    }
}

Demo.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.BLL.Repositories;
using Demo.DAL.Models;
using Demo.PL.Helpers;
using Demo.PL.viewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
	[Authorize]
	public class EmployeeController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public EmployeeController(IUnitOfWork unitOfWork,
            IMapper mapper)
        {
            _unitOfWork = unitOfWork;

            _mapper = mapper;
        }

   
        public async Task<IActionResult> Index(string SearchValue)
        {
            IEnumerable<Employee> employees;
            if (string.IsNullOrEmpty(SearchValue))

                employees = await _unitOfWork.EmployeeRepository.GetAll();

            else

                employees =  _unitOfWork.EmployeeRepository.GetEmployeeByName(SearchValue);
            var MappedEmployee = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employees);
            return View(MappedEmployee);

        }

        public IActionResult Create()
        {
            //ViewBag.Departments = _departmentRepository.GetAll();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(EmployeeViewModel employeeVM)
        {
            if (ModelState.IsValid)     
            {
                if(employeeVM.Image is not null)
               
                employeeVM.ImageName=DocumentSettings.UploadFile(employeeVM.Image, "Images");
               
 

                var MappedEmployee = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
                await _unitOfWork.EmployeeRepository.Add(MappedEmployee);
                int Result = await _unitOfWork.Complete();
                if (Result > 0)
                {
                    TempData["Message"] = $"Employee {employeeVM.Name} is Created ";

                }

                return RedirectToAction(nameof(Index));
            }
            return View(employeeVM);

        }

        public async Task<IActionResult> Details(int? id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var employee = await _unitOfWork.EmployeeRepository.GetById(id.Value);
            if (employee is null)
                return NotFound();
            var MappedEmployee = _mapper.Map<Employee, EmployeeViewModel>(employee);
            return View(ViewName, MappedEmployee);

        }

        public async Task<IActionResult> Edit(int? id)
        {
            //if(id is null)
            //     return BadRequest();
            // var employee = _employeerepository.GetById(id.Value);
            // if(employee is null)
            //     return NotFound();
            // return View(employee);
            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EmployeeViewModel employeeVM, [FromRoute] int id)
        {
            if (id != employeeVM.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    if(employeeVM.Image is not null)
                    {
                        employeeVM.ImageName = DocumentSettings.UploadFile(employeeVM.Image, "Images");
                    }
 
                    
                    var MappedEmployee = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
                    _unitOfWork.EmployeeRepository.Update(MappedEmployee);
                    await _unitOfWork.Complete();
                    return RedirectToAction(nameof(Index));

                }
                catch (System.Exception ex)
                {

                    ModelState.AddModelError(string.Empty, ex.Message);
                }

            }
            return View(employeeVM);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            return await Details(id, "Delete");

        }
        
        [HttpPost]
        public async Task<IActionResult> Delete(EmployeeViewModel employeeVM, [FromRoute] int id)
        {
            if (id != employeeVM.Id)
                return BadRequest();
            try
            {
                var MappedEmployee = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
                _unitOfWork.EmployeeRepository.Delete(MappedEmployee);
                var Result = await _unitOfWork.Complete();
                if(Result > 0&&employeeVM.ImageName is not null)
                {
                    DocumentSettings.DeleteFile("Images", employeeVM.ImageName);
                }
                return RedirectToAction(nameof(Index));

            }
            catch (System.Exception ex )
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                return View(employeeVM);
            }
        }
    }
}

Demo.PL/Controllers/RoleController.cs
using AutoMapper;
using Demo.DAL.Models;
using Demo.PL.viewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IMapper _mapper;

        public RoleController(RoleManager<IdentityRole> roleManager , IMapper mapper)
        {
                _roleManager = roleManager;
            _mapper= mapper;
        }
        public async Task<IActionResult> Index(string SearchValue)
        {
            if (string.IsNullOrEmpty(SearchValue))
            {
                var Roles = await _roleManager.Roles.ToListAsync();
                var MappedRoles =  _mapper.Map<IEnumerable<IdentityRole>, IEnumerable<RoleViewModel>>(Roles);
                return View(MappedRoles);
            }
            else
            {
               var Roles = _roleManager.FindByNameAsync(SearchValue);
                var MappedRoles = _mapper.Map<IdentityRole, RoleViewModel>(Roles.Result);
                return View(new List<RoleViewModel>() { MappedRoles });
            }
             
        }

        public IActionResult Create() 
        { 
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel model )
        {
            if (ModelState.IsValid) 
            {
               var MappedRole = _mapper.Map<RoleViewModel,IdentityRole>(model);
                await _roleManager.CreateAsync(MappedRole);
                return RedirectToAction("Index");
            }
            return View(model);
        }


        public async Task<IActionResult> Details(string id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var Role = await _roleManager.FindByIdAsync(id);
            if (Role is null)
                return NotFound();
            var MappedRole = _mapper.Map<IdentityRole, RoleViewModel>(Role);
            return View(ViewName, MappedRole);

        }

        public async Task<IActionResult> Edit(string id)
        {
            return await Details(id, "Edit");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RoleViewModel model, [FromRoute] string id)
        {
            if (id != model.id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    var Role = await _roleManager.FindByIdAsync(id);

                    Role.Name = model.RoleName;

 
                    await _roleManager.UpdateAsync(Role);
                    return RedirectToAction(nameof(Index));
                }
                catch (System.Exception ex)
                {

                    ModelState.AddModelError(string.Empty, ex.Message);
                }

            }


            return View(model);

        }

        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmDelete(RoleViewModel model, [FromRoute] string id)
        {

            if (id!= model.id)
                return BadRequest();
            try
            {

                var Role = await _roleManager.FindByIdAsync(id);

                await _roleManager.DeleteAsync(Role);
                return RedirectToAction(nameof(Index));
            }
            catch (System.Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                return RedirectToAction("Error", "Home");
            }
        }
    }
}

Demo.PL/Controllers/UserController.cs
using AutoMapper;
using Demo.DAL.Models;
using Demo.PL.viewModels;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
	public class UserController : Controller
	{
		public UserManager<ApplicationUser> _userManager { get; }

        private readonly IMapper _mapper;

        public UserController(UserManager<ApplicationUser> userManager , IMapper mapper)
        {
			_userManager=userManager;
            _mapper = mapper;
        }



		public async Task<IActionResult> Index(string Searchvalue)
		{
			if(string.IsNullOrEmpty(Searchvalue))
			{
				var users = await _userManager.Users.Select( U=> new UserViewModel
				{
					Id = U.Id,
					FName = U.FName,
					LName = U.LName,
					PhoneNumber = U.PhoneNumber,
					Roles = _userManager.GetRolesAsync(U).Result

				}).ToListAsync();
				return View(users);
			}
            else
            {
                var user = await _userManager.FindByNameAsync(Searchvalue);

                if (user == null)
                {
                    // User was not found, handle this scenario
                    ModelState.AddModelError(string.Empty, "User not found.");
                    return View(new List<UserViewModel>()); // Or return a different view/message
                }

                var MappedUser = new UserViewModel()
                {
                    Id = user.Id,
                    FName = user.FName,
                    LName = user.LName,
                    Email = user.Email,
                    PhoneNumber = user.PhoneNumber,
                    Roles = _userManager.GetRolesAsync(user).Result.ToList()
                };

                return View(new List<UserViewModel> { MappedUser });
            }

        }


        public async Task<IActionResult> Details(string id , string ViewName = "Details")
		{
			if (id is null)
                return BadRequest();
			 var user = await _userManager.FindByIdAsync(id);
			if ( user is null )
				return NotFound();
			var MappedUser = _mapper.Map<ApplicationUser, UserViewModel>(user);
			return View(ViewName, MappedUser);
 
        }

        public async Task<IActionResult> Edit(string id )
        {
            return await Details(id, "Edit");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserViewModel model , [FromRoute] string id )
        {
            if (id != model.Id)
                return BadRequest();
            if (ModelState.IsValid)
            {
                try
                {
                    var User = await _userManager.FindByIdAsync(id);
                    User.FName = model.FName;
                    User.LName = model.LName;
                    User.PhoneNumber = model.PhoneNumber;
                    await _userManager.UpdateAsync( User);
                    return RedirectToAction(nameof(Index));
                }
                catch (System.Exception ex)
                {

                    ModelState.AddModelError(string.Empty, ex.Message); 
                }

            }
             
            
                return View(model); 
           
        }

        public async Task<IActionResult> Delete(string id) 
        { 
            return await Details(id,"Delete");
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmDelete(UserViewModel model , [FromRoute] string id ) 
        {

            if (id!= model.Id)
                return BadRequest();
            try
            {
           
                var user= await _userManager.FindByIdAsync(id);
 
                await _userManager.DeleteAsync(user);
                return RedirectToAction(nameof(Index));
            }
            catch (System.Exception ex)
            {

                ModelState.AddModelError(string.Empty,ex.Message);
                return RedirectToAction("Error","Home");
            }
        }
	}
}

Demo.PL/Views/Shared/_AuthLayout.cshtml
 
<!DOCTYPE html>
<html>
<head>
	<title>@ViewData["Title"]</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
 
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
    <!-- //web font -->
    @* <link href="~\css\authstylesheet.css" rel="stylesheet" /> *@
	<link rel="stylesheet" href="~/css/authstylesheet.css">

</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
           @RenderBody()
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
 
	@await RenderSectionAsync("_ValidationScriptSection", required: true)
</body>
</html>

Demo.PL/Views/Shared/_ButtonPartialView.cshtml
@model string 
<td><a asp-action="Details" asp-route-id="@Model"><i class="fas fa-eye" style="color: yellow;"></i></a></td>
<td><a asp-action="Edit" asp-route-id="@Model"><i class="fas fa-edit text-success"></i></a></td>
<td><a asp-action="Delete" asp-route-id="@Model"><i class="fas fa-trash text-danger"></i></a></td>

Demo.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.PL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>

                        <li class="nav-item ml-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @* @await RenderSectionAsync("Scripts", required: false) *@
    @await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>